version: '2'
services:
  hfflat:
    privileged: true
    image: 10.15.97.250/rancher/rancher-cni-driver:v0.2
    command: /bin/sh -c "while true; do modprobe ebtables; echo -e \"CNI_INTERFACE_NAME=\"$CNI_INTERFACE_NAME'\\n''CNI_CATTLE_IPADDR='$CNI_CATTLE_IPADDR > /opt/cni/conf; sleep 60; done"
    network_mode: host
    environment:
      CNI_INTERFACE_NAME: '${CNI_INTERFACE_NAME}'
    volumes:
    - /lib/modules:/lib/modules
    - /dev:/dev
    pid: host
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent_service.hfflat: 'true'
      io.rancher.network.cni.binary: 'rancher-cni-bridge'
      io.rancher.container.dns: 'true'